[tox]
no_package = True
skip_missing_interpreters = True
env_list = integration
min_version = 4.0.0

[vars]
charm_src_path = {tox_root}/charm/src
charm_tst_path = {tox_root}/charm/tests

[testenv]
set_env =
    PYTHONPATH = {tox_root}/charm/lib:{[vars]charm_src_path}
    PYTHONBREAKPOINT=pdb.set_trace
    PY_COLORS=1
pass_env =
    PYTHONPATH
    CHARM_BUILD_DIR
    MODEL_SETTINGS

[testenv:integration]
description = Run integration tests
deps =
    pytest
    juju
    pytest-operator
    -r {tox_root}/charm/requirements.txt
commands =
    pytest -v \
           -s \
           --tb native \
           --log-cli-level=INFO \
           {posargs} \
           {[vars]charm_tst_path}/integration
