name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    uses: canonical/operator-workflows/.github/workflows/publish_charm.yaml@main
    with:
      resource-mapping: '{"roadmap-web-rock": "app-image"}'
    secrets: inherit
